#!/usr/bin/bash

PATH="/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:$PATH"
export PATH

export XDG_CURRENT_DESKTOP=Budgie:GNOME
export XDG_MENU_PREFIX="gnome-"
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"

# See: https://bugs.chromium.org/p/chromium/issues/detail?id=1514700
export CHROMIUM_FLAGS=--password-store=basic

# This is with lightdm:
(budgie-desktop) &

# Allow mopidy user to access X server
(xhost +SI:localuser:mopidy || true) &

export MOZ_USE_XINPUT2=1

# Setting sound
(amixer cset numid=3 1 || true) &
(amixer sset -D pulse Master 98% unmute || true) &
(amixer sset Master 98% unmute || true) &
#(amixer -c 1 cset numid=1 98% || true) &

/usr/local/bin/bbn-launcherd &

(rm -rf ~/.config/*nativefier*/Cache/ || true) &
(cp .config/signalk-nativefier-*/Cookies .config/sk-autopilot-nativefier-*/ || true) &
(rm -rf ~/.opencpn/startcheck.dat ~/.opencpn/_OpenCPN_SILock || true) &

# Started via /usr/share/gnome-session/sessions/org.buddiesofbudgie.BudgieDesktop.session
#(openbox --replace) &

(evdev-rce || true) &
(twofing --click=first --grab-by-disabling /dev/twofingtouch || true) &

# see: https://github.com/bareboat-necessities/lysmarine_gen/issues/316
#(sleep 30 && autoadb scrcpy -s '{}') &

# see: https://github.com/bareboat-necessities/lysmarine_gen/issues/391
(sleep 10 && systemctl --user restart pipewire-pulse.service) &

(sleep 60 && sh -c 'while ! ping -c 1 -n -w 1 spotify.com; do sleep 20; done;' && \
  systemctl --user reenable raspotify && systemctl --user start raspotify) &

(sleep 10 && shairport-sync) &

(sleep 3 && /opt/bbn-launcher/bbn-launcher) &
(sleep 3 && onboard) &

# started differently now
#(sleep 10 && ibus-daemon -r) &

#(sleep 15 && /usr/libexec/geoclue-2.0/demos/agent) &

#(sleep 3 && nm-applet --indicator) & # --indicator option gives more extended menu
#(sleep 3 && nm-applet) &

(sleep 4 && \
 xset s off && \
 xset -dpms && \
 xset s noblank) &


