#!/bin/bash
application=$(basename "$1")

DESKTOP_SESSION=gnome
export DESKTOP_SESSION

PATH=.:$PATH
export PATH

if pidof $(command -v "$1") > /dev/null ; then
    echo "${application} is already running"
    wmctrl -x -R "$application"
else
    $@
fi
